# SPDX-License-Identifier: Apache-2.0
"""Gold labels for the everyday pack's fixture corpus: what each row's
expected outcome was established under, captured when the scenarios run.

Run ``python -m tests.test_pack_everyday_gold_labels`` to rewrite
``fixtures/gold_labels.yaml`` after regenerating the fixture ledger.

Each row carries three orthogonal labels, never folded into one another:

- population (declared per n/a constraint in ``decision_table.yaml``):
  ``a`` the rule applied and a named field was missing ("correct decline"),
  ``b`` the record does not say why the rule did not settle ("recording
  defect"), ``c`` the rule did not apply (never scored);
- ``evaluator_tier``: ``recomputed`` (a deterministic predicate produced it)
  or ``judged`` (a model produced it) -- named so it cannot be confused with
  an obligation's gating tier;
- ``judge_pin_digest``: required on a judged row, forbidden on a recomputed
  row.

and two identities: ``config_identity`` (the pack and the digest of every
wicket that ran) and ``code_identity`` (below).

``code_identity`` is a LOCAL, INTERIM field, pending a field in the Agent
Action Capsule evidence-result schema [recomputed-tier-code-identity]. When
that field lands, this one is renamed onto it, never kept beside it. It is
``{kind, value, assurance}``: ``kind`` is ``source_tree_sha256`` (SHA-256
over the sorted ``"<path>\\0<sha256 of file>\\n"`` lines of the
verdict-producing source, see ``CODE_SCOPE``) or ``git_commit``; ``value`` is
the digest or commit, or ``"unknown"`` when it could not be resolved at
check time; ``assurance`` is a level from the existing ladder (self-attested
| witnessed | countersigned). Its limit: a code identity is a claim made by
whoever built the artifact (self-attested). It makes rows COMPARABLE -- the
same code across a window -- not CHECKABLE: a stranger cannot confirm it
from the receipt.

A recomputed row whose code identity is missing or ``"unknown"`` cannot be
reproduced, so it is classified population ``b`` -- never relabelled
``judged``. Population ``b`` is a regression detector: zero in a conforming
build; nonzero means the n/a invariant was bypassed or a foreign producer
wrote the record. It is counted on its own and never enters a rate.
"""
from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

import pytest
import yaml
from capsule_ledger.ledger import LedgerStore

from capsule_engine.packs.loader import load_pack_dir
from capsule_engine.packs.schema import NORMALIZED_ACTION_FIELDS
from capsule_engine.report.result_from_folds import project_guard_constraint

REPO = Path(__file__).parent.parent
PACK_DIR = REPO / "capsule_engine" / "packs" / "catalog" / "everyday"
GOLD_PATH = PACK_DIR / "fixtures" / "gold_labels.yaml"
LEDGER_PATH = PACK_DIR / "fixtures" / "mini_ledger.jsonl"

# The source that produces a guard verdict: the checks and engine, the fold
# engine caps reads, and the pack/manifest path that configures them.
CODE_SCOPE = ("capsule_engine/guards", "capsule_engine/folds", "capsule_engine/policy", "capsule_engine/packs")
EVALUATOR_TIERS = frozenset({"recomputed", "judged"})
ASSURANCE_LEVELS = frozenset({"self-attested", "witnessed", "countersigned"})
CODE_IDENTITY_KINDS = frozenset({"source_tree_sha256", "git_commit"})
_HEX64 = re.compile(r"^[0-9a-f]{64}$")
_HEX40 = re.compile(r"^[0-9a-f]{40}$")

HEADER = """\
# Gold labels for the everyday fixture corpus. GENERATED by
# `python -m tests.test_pack_everyday_gold_labels` from the scenario run that
# produced mini_ledger.jsonl -- except the row marked hand_authored, which is
# a deliberate constant and must never be replaced by engine output.
# Population per n/a constraint is declared in decision_table.yaml.
#
# code_identity: a local, interim field, pending a field in the Agent Action
# Capsule evidence-result schema [recomputed-tier-code-identity]; renamed onto
# that field when it lands, never kept beside it. A code identity is a claim
# by whoever built the artifact (self-attested): it makes rows comparable
# across a window, not checkable by a stranger from the receipt.
"""

# Population b, hand-authored: the verify_before_dispatch record exactly as
# the engine sealed it before every n/a carried a facts object -- payments-safety
# fixture capsule 1870189b2e23c0c86ea95f2b945ffff33ec430da295ff7348eefee60efff7ad9
# at capsule-engine 3e6e5014533c07517fea6779bf50d996ca5c57c1. The fixed engine
# cannot emit this shape, so it cannot come from a scenario run.
RECORDING_DEFECT_ROW = {
    "hand_authored": True,
    "action_id": "dispatch_payout/payments-safety-fixture-caps-allow",
    "capsule_id": "1870189b2e23c0c86ea95f2b945ffff33ec430da295ff7348eefee60efff7ad9",
    "record": {
        "id": "verify_before_dispatch",
        "result": "n/a",
        "severity": "blocking",
        "check_type": "policy",
        "method": "agent_action_capsule.verify",
    },
    "declared_population": "b",
    "evaluator_tier": "recomputed",
    "config_identity": {
        "pack_id": "asg/payments-safety/1.0.0",
        "pack_digest": "81278051db5ca3755956b7adeaea727d333d12a0c14c51c7e030f15ea8b9666f",
        "wickets": {
            "payments_safety.verify_before_dispatch/1.0.0": (
                "e60e9eef35f0f4529dac627cea7298f71f4d1c1096bf6317b3f05a46bbaa1c11"
            )
        },
    },
    "code_identity": {
        "kind": "git_commit",
        "value": "3e6e5014533c07517fea6779bf50d996ca5c57c1",
        "assurance": "self-attested",
    },
}


def source_tree_sha256(repo: Path = REPO) -> str:
    lines = []
    for scope in CODE_SCOPE:
        for path in sorted((repo / scope).rglob("*.py")):
            rel = path.relative_to(repo).as_posix()
            lines.append(f"{rel}\0{hashlib.sha256(path.read_bytes()).hexdigest()}\n")
    return hashlib.sha256("".join(sorted(lines)).encode("utf-8")).hexdigest()


class GoldLabelError(ValueError):
    pass


def classify(row: dict) -> str:
    """Validate one gold-label row and return the population it is scored in.

    A declared population stands unless the row cannot be reproduced: a
    recomputed row with no resolvable code identity is population ``b``."""
    tier = row.get("evaluator_tier")
    if tier not in EVALUATOR_TIERS:
        raise GoldLabelError(f"evaluator_tier must be one of {sorted(EVALUATOR_TIERS)}, got {tier!r}")
    if "tier" in row:
        raise GoldLabelError("a gold-label row names its evaluator tier evaluator_tier, never tier")
    pin = row.get("judge_pin_digest")
    if tier == "judged" and not (isinstance(pin, str) and _HEX64.match(pin)):
        raise GoldLabelError("a judged row must carry judge_pin_digest (64 hex)")
    if tier == "recomputed" and pin is not None:
        raise GoldLabelError("a recomputed row must not carry judge_pin_digest")

    code = row.get("code_identity")
    if code is not None:
        if not isinstance(code, dict):
            raise GoldLabelError("code_identity must be {kind, value, assurance}, never a bare value")
        if code.get("assurance") not in ASSURANCE_LEVELS:
            raise GoldLabelError(f"code_identity.assurance must be one of {sorted(ASSURANCE_LEVELS)}")
        if code.get("kind") not in CODE_IDENTITY_KINDS:
            raise GoldLabelError(f"code_identity.kind must be one of {sorted(CODE_IDENTITY_KINDS)}")
        value = code.get("value")
        pattern = _HEX64 if code["kind"] == "source_tree_sha256" else _HEX40
        if value != "unknown" and not (isinstance(value, str) and pattern.match(value)):
            raise GoldLabelError(f"code_identity.value {value!r} is neither a {code['kind']} nor 'unknown'")
    if tier == "recomputed" and (code is None or code.get("value") == "unknown"):
        return "b"
    return row["declared_population"]


def build_rows(pack, installed_wickets: dict[str, str], ledger_lines: list[str], code_value: str) -> list[dict]:
    rows = []
    for line in ledger_lines:
        capsule = json.loads(line)
        if "constraints" not in capsule:
            continue
        ran = {c["id"] for c in capsule["constraints"]}
        rows.append(
            {
                "action_id": capsule["action_id"],
                "capsule_id": capsule["capsule_id"],
                "evaluator_tier": "recomputed",
                "config_identity": {
                    "pack_id": pack.pack_id,
                    "pack_digest": pack.definition_digest(),
                    "wickets": {w.wicket_id: installed_wickets[w.wicket_id] for w in pack.constraints if w.check in ran},
                },
                "code_identity": {"kind": "source_tree_sha256", "value": code_value, "assurance": "self-attested"},
            }
        )
    return rows


def _run_scenarios(ledger, *, project_dir):
    """The everyday acceptance scenario script, loaded by path so this works
    under pytest and under ``python -m`` alike."""
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "everyday_acceptance", Path(__file__).with_name("test_pack_everyday_acceptance.py")
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module._run_scenarios(ledger, project_dir=project_dir)


def _write(rows: list[dict]) -> None:
    body = yaml.safe_dump({"rows": rows + [RECORDING_DEFECT_ROW]}, sort_keys=False, width=120)
    GOLD_PATH.write_text(HEADER + body)


def _regenerate() -> None:
    import tempfile

    code_value = source_tree_sha256()  # captured at check time, before the run
    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        store = LedgerStore(tmp / "ledger")
        try:
            installed, _, _, records = _run_scenarios(store, project_dir=tmp / "project")
        finally:
            store.close()
    lines = [json.dumps(r.capsule, separators=(",", ":")) for r in records]
    if lines != LEDGER_PATH.read_text().splitlines():
        raise SystemExit("regenerate mini_ledger.jsonl first (python -m tests.test_pack_everyday_acceptance)")
    wickets = {w.wicket_id: w.digest for w in installed.manifest.wickets}
    _write(build_rows(installed.pack, wickets, lines, code_value))
    print(f"wrote {GOLD_PATH}")


# -- tests ---------------------------------------------------------------------


def _gold() -> list[dict]:
    return yaml.safe_load(GOLD_PATH.read_text())["rows"]


def _declared_populations() -> dict[str, str]:
    """action_id -> 'a' if any n/a constraint on that row is declared a, else 'c'
    (or 'settled' when the row recorded no in-scope n/a)."""
    table = yaml.safe_load((PACK_DIR / "fixtures" / "decision_table.yaml").read_text())["rows"]
    return {
        row["action_id"]: "a" if any(d["population"] == "a" for d in row["n_a"].values()) else "c" for row in table
    }


def test_one_generated_row_per_decision_capsule_plus_the_hand_authored_row():
    decisions = [json.loads(line) for line in LEDGER_PATH.read_text().splitlines()]
    decision_ids = [c["action_id"] for c in decisions if "constraints" in c]
    gold = _gold()
    generated = [r for r in gold if not r.get("hand_authored")]
    assert [r["action_id"] for r in generated] == decision_ids
    assert [r for r in gold if r.get("hand_authored")] == [RECORDING_DEFECT_ROW]


def test_every_row_validates_and_classifies():
    declared = _declared_populations()
    for row in _gold():
        if row.get("hand_authored"):
            assert classify(row) == "b"
            continue
        assert classify(dict(row, declared_population=declared[row["action_id"]])) == declared[row["action_id"]]


def test_the_hand_authored_row_projects_as_a_recording_defect():
    projected = project_guard_constraint(
        RECORDING_DEFECT_ROW["record"], candidate_fields=frozenset(NORMALIZED_ACTION_FIELDS)
    )
    assert projected.recording_defect is True
    assert projected.sufficiency == "UNKNOWN"


def test_rerunning_each_row_from_its_recorded_pins_reproduces_its_record():
    """Each generated row's pins still resolve, and replaying the scenarios
    reproduces every recorded capsule_id -- the capsule bytes, verdict
    included -- exactly."""
    assert source_tree_sha256() == _gold()[0]["code_identity"]["value"], (
        "the verdict-producing source changed since the gold labels were captured; "
        "regenerate them with python -m tests.test_pack_everyday_gold_labels"
    )
    pack = load_pack_dir(PACK_DIR)
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        store = LedgerStore(Path(tmp) / "ledger")
        try:
            installed, _, capsules, _ = _run_scenarios(store, project_dir=Path(tmp) / "project")
        finally:
            store.close()
    replayed = {c["action_id"]: c for c in capsules.values()}
    installed_wickets = {w.wicket_id: w.digest for w in installed.manifest.wickets}
    for row in (r for r in _gold() if not r.get("hand_authored")):
        assert row["config_identity"]["pack_digest"] == pack.definition_digest()
        for wicket_id, digest in row["config_identity"]["wickets"].items():
            assert installed_wickets[wicket_id] == digest, (row["action_id"], wicket_id)
        assert replayed[row["action_id"]]["capsule_id"] == row["capsule_id"], row["action_id"]


# -- the validator itself --------------------------------------------------------


def _row(**overrides) -> dict:
    row = {
        "evaluator_tier": "recomputed",
        "declared_population": "a",
        "code_identity": {"kind": "source_tree_sha256", "value": "a" * 64, "assurance": "self-attested"},
    }
    row.update(overrides)
    return row


def test_a_recomputed_row_missing_code_identity_lands_in_b_not_judged():
    row = _row()
    del row["code_identity"]
    assert classify(row) == "b"
    assert row["evaluator_tier"] == "recomputed"
    unknown = _row(code_identity={"kind": "source_tree_sha256", "value": "unknown", "assurance": "self-attested"})
    assert classify(unknown) == "b"


def test_a_judged_row_must_carry_a_judge_pin_and_a_recomputed_row_must_not():
    with pytest.raises(GoldLabelError, match="judged row must carry"):
        classify(_row(evaluator_tier="judged"))
    assert classify(_row(evaluator_tier="judged", judge_pin_digest="c" * 64)) == "a"
    with pytest.raises(GoldLabelError, match="must not carry"):
        classify(_row(judge_pin_digest="c" * 64))


@pytest.mark.parametrize(
    "code",
    [
        "a" * 64,
        {"kind": "source_tree_sha256", "value": "a" * 64},
        {"kind": "source_tree_sha256", "value": "a" * 64, "assurance": "trusted"},
        {"kind": "version", "value": "0.0.1", "assurance": "self-attested"},
        {"kind": "git_commit", "value": "0.0.1", "assurance": "self-attested"},
    ],
)
def test_code_identity_refuses_a_bare_value_a_missing_assurance_or_a_version_string(code):
    with pytest.raises(GoldLabelError):
        classify(_row(code_identity=code))


def test_a_bare_tier_key_is_refused():
    with pytest.raises(GoldLabelError, match="evaluator_tier"):
        classify(_row(tier="recomputed"))


# -- the interim field never appears without its declaration ---------------------

FIELD = "code_identity"
DECLARATION = "[recomputed-tier-code-identity]"


def _files_missing_declaration(files: list[Path]) -> list[str]:
    return [str(p) for p in files if FIELD in p.read_text(errors="ignore") and DECLARATION not in p.read_text(errors="ignore")]


def test_the_interim_field_never_appears_without_its_declaration(tmp_path):
    # Positive control: a planted file using the field with no declaration.
    planted = tmp_path / "planted.py"
    planted.write_text(f"row = {{'{FIELD}': None}}\n")
    assert _files_missing_declaration([planted]) == [str(planted)]

    tracked = [p for p in REPO.rglob("*") if p.is_file() and ".git" not in p.parts and p.suffix in {".py", ".yaml", ".md"}]
    users = [p for p in tracked if FIELD in p.read_text(errors="ignore")]
    assert {p.name for p in users} == {"gold_labels.yaml", Path(__file__).name}
    assert _files_missing_declaration(tracked) == []


if __name__ == "__main__":
    _regenerate()
